check spam
js-tasks-ru/jsbasic-20211108_stanislavg pull request #5
Opened 2021-11-16 17:26 UTC by olga2102

2021-11-16 17:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-17 16:43 UTC, SinimaWath requested changes

2021-11-17 16:43 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  console.log(lowercaseStr);
Это можно убрать

2021-11-17 16:43 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return lowercaseStr.includes('1xBet'.toLowerCase()) || ....`

Это как раз тот случай

2021-11-17 16:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-18 17:09 UTC, SinimaWath approved these changes
все ок :)

2021-11-18 17:09 UTC, merged